### ISSUE TITLE
mlagents_envs.exception.UnityActionException 오류

### ISSUE THREAD

**Issue by sehi0129** [reinforcement-learning-kr/Unity_ML_Agents_2.0#61]
안녕하세요 유니티 심층 강화 학습 교재를 보고 공부하고 있습니다
cmd에서 py를 실행하였을 때 오류가 이렇게 뜨는데
환경에서 문제가 발생하는 거 같습니다
그런 게 어떻게 해결해야 할지 잘 몰라서 질문 남겨봅니다
좋은 교재 감사합니다.

load_model = False
train_mode = True 

... Save Model to ./saved_models/Kart/BC/20230731164421/ckpt ...
410 Epoch / Loss: 0.00209520
420 Epoch / Loss: 0.00184623
430 Epoch / Loss: 0.00186352
440 Epoch / Loss: 0.00186342
450 Epoch / Loss: 0.00183344
460 Epoch / Loss: 0.00179485
470 Epoch / Loss: 0.00177195
480 Epoch / Loss: 0.00185431
490 Epoch / Loss: 0.00167553
500 Epoch / Loss: 0.00171051
... Save Model to ./saved_models/Kart/BC/20230731164421/ckpt ...
PLAY START
Traceback (most recent call last):
  File "Kart.py", line 169, in <module>
    env.set_actions(behavior_name, action_tuple)
  File "C:\Users\sehi\AppData\Local\Programs\Python\Python38\lib\site-packages\mlagents_envs\environment.py", line 358, in set_actions
    action = action_spec._validate_action(action, num_agents, behavior_name)
  File "C:\Users\sehi\AppData\Local\Programs\Python\Python38\lib\site-packages\mlagents_envs\base_env.py", line 428, in _validate_action
    raise UnityActionException(
mlagents_envs.exception.UnityActionException: The behavior ArcadeDriver?team=0 needs a discrete input of dimension (1, 2) for (<number of agents>, <action size>) but received input of dimension (1, 0)

--------------------------------------------

load_model = True
train_mode = False 

Traceback (most recent call last):
  File "Kart.py", line 169, in <module>
    env.set_actions(behavior_name, action_tuple)
  File "C:\Users\sehi\AppData\Local\Programs\Python\Python38\lib\site-packages\mlagents_envs\environment.py", line 358, in set_actions
    action = action_spec._validate_action(action, num_agents, behavior_name)
  File "C:\Users\sehi\AppData\Local\Programs\Python\Python38\lib\site-packages\mlagents_envs\base_env.py", line 428, in _validate_action
    raise UnityActionException(
mlagents_envs.exception.UnityActionException: The behavior ArcadeDriver?team=0 needs a discrete input of dimension (1, 2) for (<number of agents>, <action size>) but received input of dimension (1, 0)

**Comment by sehi0129** [comment]
해결했습니다

**Comment by Kyushik** [comment]
아이고 액션에 대한 dimension 문제일 것 같다고 답글을 남긴줄 알았는데 안남겼었네요 ㅜㅜ 혹시 관련해서 해결법 공유주실 수 있으실까요? 다른분들께 도움이 될 것 같습니다!

**Comment by sehi0129** [comment]
-----Original Message-----
